"""empty message

Revision ID: 764296632d80
Revises: 3fc053bb5ec4
Create Date: 2021-02-14 22:13:38.917848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764296632d80'
down_revision = '3fc053bb5ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headPhoto', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'headPhoto')
    # ### end Alembic commands ###
